source "https://rubygems.org"
gem "sinatra", "~> 4.0"

gem "sinatra-contrib", "~> 4.0"

gem "rack-test", "~> 2.1"

gem "coderay", "~> 1.1"

gem "rspec", "~> 3.13"


gem "rackup", "~> 2.1"

gem "sequel", "~> 5.82"

gem "sqlite3", "~> 2.0"

gem "mail", "~> 2.8"

gem "dotenv", "~> 3.1"
gem "httpx", "~> 1.3"
